### ISSUE TITLE
Crash on openvix python 3

### ISSUE THREAD

**Issue by davesayers2014** [oe-mirrors/e2iplayer#1]
Hi I have a  crash when trying to open the plugin on openvix python 3

[Enigma2_crash_2021-06-27_23-02-30.log](https://github.com/oe-mirrors/e2iplayer/files/6722451/Enigma2_crash_2021-06-27_23-02-30.log)

Openvix python 3 branch 

> https://github.com/OpenViX/enigma2/tree/Dev-python3-compatible

`< 27264.5415> Traceback (most recent call last):
< 27264.5416>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 60, in action
< 27264.5421>     res = self.actions[action]()
< 27264.5422>   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 167, in save
< 27264.5426>     self.run()
< 27264.5426>   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 171, in run
< 27264.5430>     plugin(session=self.session)
< 27264.5430>   File "/usr/lib/enigma2/python/Plugins/Plugin.py", line 108, in __call__
< 27264.5434>     return self._fnc(*args, **kwargs)
< 27264.5434>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/plugin.py", line 112, in main
< 27264.5438>     runMain(session)
< 27264.5438>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/plugin.py", line 137, in runMain
< 27264.5442>     nextFunction(session)
< 27264.5442>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/plugin.py", line 133, in doRunMain
< 27264.5446>     session.open(E2iPlayerWidget)
< 27264.5446>   File "/usr/lib/enigma2/python/StartEnigma.py", line 345, in open
< 27264.5452>     self.execBegin()
< 27264.5452>   File "/usr/lib/enigma2/python/StartEnigma.py", line 266, in execBegin
< 27264.5456>     c.show()
< 27264.5457>   File "/usr/lib/enigma2/python/Screens/Screen.py", line 136, in show
< 27264.5460>     x()
< 27264.5461>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerwidget.py", line 1147, in onStart
< 27264.5476>     self.askUpdateAvailable(self.selectHost)
< 27264.5477>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerwidget.py", line 1167, in askUpdateAvailable
< 27264.5493>     NoUpdateCallback()
< 27264.5494>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerwidget.py", line 1207, in selectHost
< 27264.5510>     self.selectGroup()
< 27264.5510>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerwidget.py", line 1223, in selectGroup
< 27264.5528>     self.session.openWithCallback(self.selectGroupCallback, PlayerSelectorWidget, inList=self.displayGroupsList, outList=self.newDisplayGroupsList, numOfLockedItems=self.getNumOfSpecialItems(self.displayGroupsList), groupName='selectgroup')
< 27264.5528>   File "/usr/lib/enigma2/python/StartEnigma.py", line 332, in openWithCallback
< 27264.5534>     dlg = self.open(screen, *arguments, **kwargs)
< 27264.5534>   File "/usr/lib/enigma2/python/StartEnigma.py", line 342, in open
< 27264.5539>     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
< 27264.5540>   File "/usr/lib/enigma2/python/StartEnigma.py", line 279, in instantiateDialog
< 27264.5549>     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
< 27264.5549>   File "/usr/lib/enigma2/python/StartEnigma.py", line 309, in doInstantiateDialog
< 27264.5555>     dlg.applySkin()
< 27264.5556>   File "/usr/lib/enigma2/python/Screens/Screen.py", line 246, in applySkin
< 27264.5560>     self.createGUIScreen(self.instance, self.desktop)
< 27264.5561>   File "/usr/lib/enigma2/python/Screens/Screen.py", line 276, in createGUIScreen
< 27264.5565>     f()
< 27264.5566>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/playerselector.py", line 307, in onStart
< 27264.5572>     self.initDisplayList()
< 27264.5572>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/playerselector.py", line 317, in initDisplayList
< 27264.5577>     self.setIdx(self.lastSelection)
< 27264.5577>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/playerselector.py", line 378, in setIdx
< 27264.5583>     self.moveMarker()
< 27264.5583>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/playerselector.py", line 433, in moveMarker
< 27264.8989>     self["marker"].instance.move(ePoint(x, y))
< 27264.8989>   File "/usr/lib/enigma2/python/enigma.py", line 1211, in __init__
< 27264.9007>     _enigma.ePoint_swiginit(self, _enigma.new_ePoint(*args))
< 27264.9008> TypeError: in method 'new_ePoint', argument 1 of type 'int'
Additional information:
Wrong number or type of arguments for overloaded function 'new_ePoint'.
  Possible C/C++ prototypes are:
    ePoint::ePoint()
    ePoint::ePoint(int,int)
< 27264.9008> 
< 27264.9009> [ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xae99de50>>,('WizardActions', 'ok')) failed)
`

**Comment by jbleyel** [comment]
ePoint should also understand float and convert this to int.

**Comment by jbleyel** [comment]
https://github.com/oe-mirrors/e2iplayer/commit/ab98978fb17b68220c17eba94952f220b57a336f
