### ISSUE TITLE
External eplayer3 does not work

### ISSUE THREAD

**Issue by MOHAMED19OS** [oe-mirrors/e2iplayer#7]
External eplayer3 does not work in python 3.10

i' test in egam10.1 & OpenATV 7.1
![screenshot_20220406051848](https://user-images.githubusercontent.com/47327706/161895249-e84764ac-6dd0-4d0e-bd23-0d0c896a8749.jpg)

**Comment by davesayers2014** [comment]
I've seen this on a forum then it works. I just used the settings command as I had the players are installed

> Use putty



opkg update;opkg install ffmpeg

opkg install exteplayer3

opkg install gstplayer

opkg install enigma2-plugin-systemplugins-serviceapp



then



init 4 && sleep 1 && echo "config.plugins.iptvplayer.exteplayer3path=/usr/bin/exteplayer3" >> /etc/enigma2/settings && init 3
